# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_cabinet_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 24px")
        self.label.setObjectName("label")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton.setGeometry(QtCore.QRect(210, 220, 201, 48))
        self.commandLinkButton.setStyleSheet("font-size: 18px")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(210, 270, 161, 48))
        self.commandLinkButton_2.setStyleSheet("font-size: 18px")
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(210, 320, 161, 48))
        self.commandLinkButton_3.setStyleSheet("font-size: 18px")
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(210, 370, 161, 48))
        self.commandLinkButton_4.setStyleSheet("font-size: 18px")
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_6.setGeometry(QtCore.QRect(210, 470, 171, 48))
        self.commandLinkButton_6.setStyleSheet("font-size: 18px")
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_5.setGeometry(QtCore.QRect(210, 420, 161, 48))
        self.commandLinkButton_5.setStyleSheet("font-size: 18px")
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 160, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 230, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(610, 400, 171, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 470, 171, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(650, 340, 81, 41))
        self.lcdNumber.setStyleSheet("color: rgb(255, 0, 4);\n"
"background-color: #ddd;\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(650, 280, 81, 61))
        self.label_2.setStyleSheet("font-size: 32px")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(490, 190, 20, 321))
        self.line.setStyleSheet("width: 5px;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Задачи"))
        self.commandLinkButton.setText(_translate("Form", "Задача 1 - 5б"))
        self.commandLinkButton_2.setText(_translate("Form", "Задача 2 - 5б"))
        self.commandLinkButton_3.setText(_translate("Form", "Задача 3 - 5б"))
        self.commandLinkButton_4.setText(_translate("Form", "Задача 4 - 5б"))
        self.commandLinkButton_6.setText(_translate("Form", "Задача 6 - 5б"))
        self.commandLinkButton_5.setText(_translate("Form", "Задача 5 - 5б"))
        self.pushButton_2.setText(_translate("Form", "Добавить еще"))
        self.pushButton_3.setText(_translate("Form", "Выйти"))
        self.pushButton.setText(_translate("Form", "Начать урок"))
        self.pushButton_4.setText(_translate("Form", "Закончить урок"))
        self.label_2.setText(_translate("Form", "Timer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
