# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_cabinet.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(653, 424)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 30, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton.setGeometry(QtCore.QRect(70, 60, 201, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(70, 110, 161, 48))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(70, 160, 161, 48))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(70, 210, 161, 48))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_6.setGeometry(QtCore.QRect(70, 310, 171, 48))
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_5.setGeometry(QtCore.QRect(70, 260, 161, 48))
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Задачи"))
        self.commandLinkButton.setText(_translate("Form", "Задача 1 - 5б"))
        self.commandLinkButton_2.setText(_translate("Form", "Задача 2 - 5б"))
        self.commandLinkButton_3.setText(_translate("Form", "Задача 3 - 5б"))
        self.commandLinkButton_4.setText(_translate("Form", "Задача 4 - 5б"))
        self.commandLinkButton_6.setText(_translate("Form", "Задача 6 - 5б"))
        self.commandLinkButton_5.setText(_translate("Form", "Задача 5 - 5б"))
        self.pushButton_2.setText(_translate("Form", "Добавить еще"))
        self.pushButton_3.setText(_translate("Form", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
