# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create-task.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(50, 400, 501, 251))
        self.textEdit.setObjectName("textEdit")

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(260, 160, 271, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(390, 290, 91, 31))
        self.spinBox.setStyleSheet("font-size: 24px")
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setValue(1)

        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setGeometry(QtCore.QRect(330, 220, 81, 31))
        self.spinBox_2.setStyleSheet("font-size: 24px")
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_2.setValue(5)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 140, 201, 61))
        self.label.setStyleSheet("font-size: 24px\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 220, 271, 31))
        self.label_2.setStyleSheet("font-size: 24px\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 290, 331, 31))
        self.label_3.setStyleSheet("font-size: 24px")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 350, 161, 31))
        self.label_4.setStyleSheet("font-size: 24px")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(570, 610, 131, 41))
        self.pushButton.setStyleSheet("font-size: 24px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 610, 131, 41))
        self.pushButton_2.setStyleSheet("font-size: 24px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 40, 281, 51))
        self.label_5.setStyleSheet("font-size: 36px")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(580, 400, 113, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(720, 400, 113, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(580, 470, 113, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(720, 470, 113, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(580, 540, 113, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(720, 540, 113, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(590, 280, 231, 51))
        self.label_6.setStyleSheet("font-size: 24px")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(610, 350, 61, 31))
        self.label_7.setStyleSheet("font-size: 24px")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(740, 350, 81, 31))
        self.label_8.setStyleSheet("font-size: 24px")
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название задачи:"))
        self.label_2.setText(_translate("Dialog", "Количество аргументов:"))
        self.label_3.setText(_translate("Dialog", "Количество баллов за задачу:"))
        self.label_4.setText(_translate("Dialog", "Текст задачи:"))
        self.pushButton.setText(_translate("Dialog", "Сохранить"))
        self.pushButton_2.setText(_translate("Dialog", "Удалить"))
        self.label_5.setText(_translate("Dialog", "Создание задачи"))
        self.label_6.setText(_translate("Dialog", "Тесты для проверки"))
        self.label_7.setText(_translate("Dialog", "Ввод"))
        self.label_8.setText(_translate("Dialog", "Вывод"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
