# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_w.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Input_win(object):
    def setupUi(self, Input_win):
        Input_win.setObjectName("Input_win")
        Input_win.resize(400, 400)
        Input_win.setMinimumSize(QtCore.QSize(400, 400))
        self.textEdit = QtWidgets.QTextEdit(Input_win)
        self.textEdit.setGeometry(QtCore.QRect(20, 80, 361, 51))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Input_win)
        self.label.setGeometry(QtCore.QRect(20, 40, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Input_win)
        self.pushButton.setGeometry(QtCore.QRect(130, 290, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Input_win)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 220, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Input_win)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 381, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.label_2.hide()
        self.retranslateUi(Input_win)
        QtCore.QMetaObject.connectSlotsByName(Input_win)

    def retranslateUi(self, Input_win):
        _translate = QtCore.QCoreApplication.translate
        Input_win.setWindowTitle(_translate("Input_win", "Form"))
        self.label.setText(_translate("Input_win", "Введите свое имя:"))
        self.pushButton.setText(_translate("Input_win", "Я админ"))
        self.pushButton_2.setText(_translate("Input_win", "Продолжить"))
        self.label_2.setText(_translate("Input_win", "Пользователь с таким именем уже существует"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Input_win = QtWidgets.QWidget()
    ui = Ui_Input_win()
    ui.setupUi(Input_win)
    Input_win.show()
    sys.exit(app.exec_())
